services:
  app:
    build:
      context: .
  
  web:
    build: nginx
    ports:
      - "8888:80"

  # psql -U admin -d products
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: mydb
    volumes:
      - "./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
