services:
  app:
    build:
      context: .
    volumes:
      - "./configs:/app/configs"
  
  web:
    build: nginx
    ports:
      - "8888:80"

  # psql -U admin -d products
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: mydb
    # ports:
    #   - "5432:5432"
    volumes:
      - "./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "db-volume:/var/lib/postgresql/data"

volumes:
  db-volume:
