networks:
  frontend:
  backend:


services:
  app:
    build:
      context: .
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=INFO
      - GUNICORN_PORT=8888
      - GUNICORN_WORKERS=1
      - GUNICORN_RELOAD=True # enable hot reload for devlopment
    #   - DEBUG=True
    # ports:
    #   - "5678:5678"
    volumes:
      - "./configs:/app/configs"
      - "./src:/app"
    networks:
      - frontend
      - backend

  web:
    build: nginx
    ports:
      - "8800:80"
    networks:
      - frontend

  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: mydb
    # ports:
    #   - "5432:5432"
    volumes:
      - "./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "db-volume:/var/lib/postgresql/data"
    networks:
      - backend
  
  conjob:
    build:
      context: .
      dockerfile: ./cronjobs/Dockerfile
    networks:
      - backend

volumes:
  db-volume:
